name: Feature request
description: Suggest a feature
body:
  - type: markdown
    attributes:
      value: |
        Oh hi there!

        To expedite issue processing please search open and closed issues before submitting a new one.
        Existing issues often contain information about workarounds, resolution, or progress updates.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability.
    validations:
      required: true
  - type: textarea
    id: desired-solution
    attributes:
      label: Describe the solution you'd like
      description: If you have a solution in mind, please describe it.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false
